package me.fzzyhmstrs.imbued_gear.material

import me.fzzyhmstrs.amethyst_imbuement.AI
import me.fzzyhmstrs.amethyst_imbuement.material.ValidatedArmorMaterial
import me.fzzyhmstrs.amethyst_imbuement.registry.RegisterBlock
import me.fzzyhmstrs.imbued_gear.IG
import me.fzzyhmstrs.imbued_gear.registry.RegisterItem
import net.minecraft.item.Items
import net.minecraft.recipe.Ingredient
import net.minecraft.sound.SoundEvents
import net.minecraft.util.Identifier
import me.fzzyhmstrs.amethyst_imbuement.registry.RegisterItem as RegisterAi

object IgArmorMaterialsConfig{
    val ARCHON = ValidatedArmorMaterial.Builder("ig_archons",SoundEvents.ITEM_ARMOR_EQUIP_LEATHER)
        .repairIngredient(AI.identity("sardonyx"))
        .enchantability(40)
        .protectionAmounts(1,2,2,1)
        .durabilityMultiplier(11)
        .build()
    val CELESTIAL = ValidatedArmorMaterial .Builder("ig_celestial",SoundEvents.ITEM_ARMOR_EQUIP_NETHERITE)
        .repairIngredient(AI.identity("celestine"))
        .enchantability(45)
        .protectionAmounts(6,11,9,6)
        .durabilityMultiplier(99,999)
        .knockbackResistance(0.2f)
        .toughness(5f)
        .build()
    val CHAMPION = ValidatedArmorMaterial.Builder("ig_champion",SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND)
        .repairIngredient(IG.identity("puresteel_ingot"))
        .enchantability(18)
        .protectionAmounts(5,10,8,5)
        .durabilityMultiplier(55,200)
        .knockbackResistance(0.05f)
        .toughness(4.5f)
        .build()
    val ELEMENTALIST = ValidatedArmorMaterial.Builder("ig_elementalist",SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND)
        .repairIngredient(setOf(AI.identity("sparking_gem"), AI.identity("glazing_gem"), AI.identity("glistening_ice")))
        .enchantability(22)
        .protectionAmounts(4,9,7,4)
        .durabilityMultiplier(33)
        .toughness(3.0f)
        .build()
    val ETERNITY = ValidatedArmorMaterial.Builder("ig_eternity",SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND)
        .repairIngredient(AI.identity("heartstone"))
        .enchantability(22)
        .protectionAmounts(4,9,7,4)
        .durabilityMultiplier(39,150)
        .knockbackResistance(0.1f)
        .build()
    val HUNTER = ValidatedArmorMaterial.Builder("ig_hunter",SoundEvents.ITEM_ARMOR_EQUIP_LEATHER)
        .repairIngredient(Identifier("rabbit_hide"))
        .enchantability(20)
        .protectionAmounts(2,7,6,2)
        .durabilityMultiplier(19)
        .toughness(2.0f)
        .build()
    val LICH_KING = ValidatedArmorMaterial.Builder("ig_lich_king",SoundEvents.ITEM_ARMOR_EQUIP_LEATHER)
        .repairIngredient(IG.identity("wither_bone"))
        .enchantability(13)
        .protectionAmounts(2,7,6,2)
        .durabilityMultiplier(15)
        .knockbackResistance(0f)
        .toughness(2.0f)
        .build()
    val SCHOLAR = ValidatedArmorMaterial.Builder("ig_scholars",SoundEvents.ITEM_ARMOR_EQUIP_LEATHER)
        .repairIngredient(AI.identity("book_of_lore"))
        .enchantability(40)
        .protectionAmounts(2,6,5,2)
        .durabilityMultiplier(13)
        .build()
    val SPELLBLADE = ValidatedArmorMaterial.Builder("ig_spellblades",SoundEvents.ITEM_ARMOR_EQUIP_ELYTRA)
        .repairIngredient(AI.identity("lethal_gem"))
        .enchantability(10)
        .protectionAmounts(4,9,7,4)
        .durabilityMultiplier(33)
        .knockbackResistance(0.05f)
        .toughness(2.0f)
        .build()
    val VOID_MAIL = ValidatedArmorMaterial.Builder("ig_void_mail",SoundEvents.ITEM_ARMOR_EQUIP_CHAIN)
        .repairIngredient(IG.identity("void_gem"))
        .enchantability(20)
        .protectionAmounts(3,8,6,3)
        .durabilityMultiplier(21)
        .toughness(3.0f)
        .build()
    val WARRIOR = ValidatedArmorMaterial.Builder("ig_warrior",SoundEvents.ITEM_ARMOR_EQUIP_IRON)
        .repairIngredient(AI.identity("glowing_fragment"))
        .enchantability(20)
        .protectionAmounts(4,10,8,4)
        .durabilityMultiplier(29)
        .toughness(3.5f)
        .build()
}